export const TRANSACTION_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED',
} as const;

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  OWNER: 'OWNER',
} as const;

export const RULE_TYPES = {
  THRESHOLD: 'THRESHOLD',
  VELOCITY: 'VELOCITY',
  GEO_MISMATCH: 'GEO_MISMATCH',
  CATEGORICAL_FREQUENCY: 'CATEGORICAL_FREQUENCY',
} as const;

export const SUPPORTED_CURRENCIES = ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'] as const;

export const TRANSACTION_CATEGORIES = [
  'FOOD_AND_DINING',
  'SHOPPING',
  'TRAVEL_AND_TRANSPORT',
  'UTILITIES_AND_BILLS',
  'ENTERTAINMENT',
  'FINANCIAL_SERVICES',
  'HEALTH_AND_WELLNESS',
  'OTHERS',
] as const;

export const DEFAULT_PAGE_LIMIT = 20;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
} as const;
