from app.schemas import TransactionInput

SAMPLE_TRANSACTIONS = [
    TransactionInput(
        id="sample-normal-1",
        transactionId="NORMAL-001",
        timestamp="2026-07-01T10:15:00Z",
        amount=42.75,
        currency="USD",
        merchant="Metro Grocery",
        merchantCategory="GROCERY",
        country="US",
        city="Austin",
        paymentMethod="CARD",
        referenceNumber="REF-1001",
        customerId="CUST-100",
    ),
    TransactionInput(
        id="sample-normal-2",
        transactionId="NORMAL-002",
        timestamp="2026-07-01T13:25:00Z",
        amount=88.2,
        currency="USD",
        merchant="City Fuel",
        merchantCategory="FUEL",
        country="US",
        city="Austin",
        paymentMethod="CARD",
        referenceNumber="REF-1002",
        customerId="CUST-101",
    ),
    TransactionInput(
        id="sample-borderline-1",
        transactionId="BORDER-001",
        timestamp="2026-07-02T02:45:00Z",
        amount=975.0,
        currency="USD",
        merchant="Electronics Hub",
        merchantCategory="ELECTRONICS",
        country="US",
        city="Denver",
        paymentMethod="CARD",
        customerId="CUST-102",
    ),
    TransactionInput(
        id="sample-anomaly-1",
        transactionId="ANOMALY-001",
        timestamp="2026-07-02T03:10:00Z",
        amount=25000.0,
        currency="EUR",
        merchant="Offshore Wire Desk",
        merchantCategory="TRANSFER",
        country="VG",
        paymentMethod="WIRE",
        description="High value transfer",
    ),
    TransactionInput(
        id="sample-anomaly-2",
        transactionId="ANOMALY-002",
        timestamp="2026-07-02T04:30:00Z",
        amount=48000.0,
        currency="USD",
        merchant="Unknown Exchange",
        merchantCategory="CRYPTO",
        country="RU",
        paymentMethod="WIRE",
    ),
]
