import { PERMISSIONS, Role, Permission } from '@anomaly/shared';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_UPDATE,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.API_KEYS_CREATE,
    PERMISSIONS.API_KEYS_DELETE,
    PERMISSIONS.UPLOADS_READ,
    PERMISSIONS.UPLOADS_CREATE,
    PERMISSIONS.UPLOADS_DELETE,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.TRANSACTIONS_DELETE,
    PERMISSIONS.RULES_READ,
    PERMISSIONS.RULES_TEST,
    PERMISSIONS.RULES_CREATE,
    PERMISSIONS.RULES_UPDATE,
    PERMISSIONS.RULES_DELETE,
    PERMISSIONS.RULES_EVALUATE,
    PERMISSIONS.ACTIVITY_READ,
  ],
  ANALYST: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.UPLOADS_READ,
    PERMISSIONS.UPLOADS_CREATE,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.RULES_READ,
    PERMISSIONS.RULES_TEST,
    PERMISSIONS.ACTIVITY_READ,
  ],
  MEMBER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.UPLOADS_READ,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],
  VIEWER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.UPLOADS_READ,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.RULES_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],
};

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role: Role, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission);
}
